// <auto-generated />
namespace DbProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CreatesCardUserUserClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatesCardUserUserClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051349288_CreatesCardUserUserClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
